server:
  port: 7979

spring:
  application:
    name: ananops-gateway

#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true
#    multipart:
#      enabled: true
#      max-request-size: 50MB
#      max-file-size: 50MB

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: annaops-provider-uac
        uri: lb://ananops-provider-uac
        predicates:
        - Path=/uac/**
        filters:
        - GwSwaggerHeaderFilter
        - StripPrefix=1
      - id: annaops-provider-imc
        uri: lb://ananops-provider-imc
        predicates:
          - Path=/imc/**
        filters:
          - GwSwaggerHeaderFilter
          - StripPrefix=1


eureka:
  client:
    instance:
      prefer-ip-address: true
    serviceUrl:
      defaultZone: http://root:root@ananops-eureka:8761/eureka/

logging:
  level: #调整相关包的 log 级别，以便排查问题
    org.springframework.cloud.gateway: debug